export const chatOnlyBlacklistEn = [
    "💦",
    "🍆",
    "✊🍆",
    "🍌",
    "🥒",
    "🌽",
    "🌭",
    "👅",
    "🌶",
    "👙",
    "🍼",
    "🖕",
    "🔞",
    "🦵",
    "👕👇",
    "👗👇",
    "👉👌",
    "❌❌❌",
    "🩱 👀",
    "👯",
    "📷 down",
    "Up 🎽",
    "꒰꒱",
    "꒰",
    "꒱",
    "⚠",
    "ᛋᛋ",
    "ꖦ",
    "࿕",
    "✙",
    "14 Words",
    "2 girls 1 cup",
    "two girls one cup",
    "one cup two girls",
    "one guy one jar",
    "2g1c",
    "4YEO",
    "53X",
    "Advanced White Society",
    "Aryan Brotherhood",
    "Atomwaffen Division",
    "Atomwaffen",
    "adult live stream",
    "adult private video",
    "adult video",
    "adult videos",
    "anal",
    "anilingus",
    "apeshit",
    "app number",
    "arse",
    "arsehole",
    "assmunch",
    "autoerotic",
    "Baby 121",
    "Blood Honour",
    "Blut und Ehre",
    "Bqby",
    "babeland",
    "baby batter",
    "baby juice",
    "baby yeah",
    "backside",
    "ball sack",
    "ball sucking",
    "bangbros",
    "bareback",
    "barenaked",
    "bastard",
    "bastardo",
    "bastinado",
    "bathroom show",
    "bbw",
    "bdsm",
    "be inside you",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "bestiality",
    "big bb",
    "big black",
    "big booms",
    "big breasts",
    "big dk",
    "big knockers",
    "bigovideotv",
    "bigtitty",
    "birdlock",
    "bitch",
    "big load",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blow job",
    "blow me",
    "blow your load",
    "blowjob",
    "blue waffle",
    "blumpkin",
    "bollocks",
    "bondage",
    "boner",
    "boobie trap",
    "boobies",
    "boobs",
    "boop",
    "boops",
    "booty call",
    "bootylover",
    "brazzers",
    "brown showers",
    "brunette action",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "buttcheeks",
    "butthole",
    "Chad",
    "Cyka blyat",
    "cam show",
    "cam shw",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cashapp",
    "cevalage",
    "channel in Teleg",
    "chocolate rosebuds",
    "chuddam",
    "cumz",
    "cift",
    "cift sow",
    "circlejerk",
    "clavage",
    "cleveland steamer",
    "clevrage",
    "clit",
    "clitoris",
    "clover clamps",
    "clusterfuck",
    "cock",
    "cocksucker",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "couple show",
    "cpl",
    "creampie",
    "cucking",
    "cumming",
    "cunnilingus",
    "cunt",
    "cupel show",
    "cupple show",
    "cuttly",
    "DETSKOE",
    "Das Reich",
    "Di c Pic",
    "darkie",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dick",
    "dik",
    "dildo",
    "dingleberries",
    "dingleberry",
    "dirty picture",
    "dirty pillows",
    "dirty sanchez",
    "dogie style",
    "dolcett",
    "dominatrix",
    "dommes",
    "donkey punch",
    "double dong",
    "double penetration",
    "dp action",
    "dry hump",
    "dvda",
    "ELI5",
    "ecchi",
    "ejaculation",
    "erotic",
    "FGRN",
    "FYEO",
    "Florian Geyer",
    "faggot",
    "fecal",
    "facecastlive",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "finger inside",
    "fingers inside",
    "fisting",
    "flash",
    "flash babe",
    "fok",
    "foot fetish",
    "footjob",
    "focking",
    "free show",
    "frotting",
    "fuck",
    "fucktards",
    "fuckyou",
    "fucking",
    "fudge packer",
    "fudgepacker",
    "fueck",
    "fugpuggler",
    "fukko",
    "full enjoy",
    "full opan",
    "full open show",
    "full opn",
    "full show",
    "futanari",
    "gspot",
    "gang bang",
    "gay sex",
    "genitals",
    "giant cock",
    "girl on",
    "girl on top",
    "girls gone wild",
    "girlsstreamonline",
    "goatcx",
    "goatse",
    "gokkun",
    "golden shower",
    "goo girl",
    "goodpoop",
    "goregasm",
    "gpay",
    "grope",
    "group sex",
    "group show",
    "grp show",
    "guro",
    "GNRN",
    "GTKRWN",
    "Goyim",
    "Horst Wessel",
    "Hui",
    "haji",
    "hand job",
    "handjob",
    "hardcore sex",
    "hentai",
    "hips",
    "homoerotic",
    "honkey",
    "hooker",
    "hooters",
    "horney",
    "horny",
    "hotmartcom",
    "hot carl",
    "hot chick",
    "hot premium",
    "hot private",
    "hot show",
    "hottiee",
    "how to kill",
    "how to murder",
    "huge fat",
    "humping",
    "ilpot8com",
    "imoim",
    "IWSN",
    "Isis",
    "incest",
    "intercourse",
    "jack off",
    "jbv",
    "jelly donut",
    "jerk off",
    "jerking",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jizz",
    "juggs",
    "KPC",
    "kike",
    "kinbaku",
    "kinkster",
    "knobbing",
    "koficom",
    "kofilinkcom",
    "leather restraint",
    "lemon party",
    "lesbi",
    "lesbian",
    "lesby",
    "lick",
    "licking",
    "likeevideo",
    "linktr",
    "linktree",
    "little hole",
    "lovemaking",
    "lovense",
    "lush",
    "Meine Ehre Heisst Treue",
    "make me come",
    "make me cum",
    "male squirting",
    "massage me",
    "mastrub",
    "masturbate",
    "masturbation",
    "melons",
    "mico",
    "mico live",
    "milf",
    "milkyyzz",
    "missionary position",
    "mom daughter",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "muff diver",
    "muffdiving",
    "my banana",
    "my goo",
    "my pines",
    "my pnis",
    "NFOC",
    "N0UDES",
    "Nend sudes",
    "nakd",
    "naked",
    "nambla",
    "nasty videos",
    "nawashi",
    "neonazi",
    "nepels",
    "nifoc",
    "nig nog",
    "nigga",
    "nigger",
    "niouple",
    "nipal",
    "niple",
    "niples",
    "niplez",
    "nipls",
    "nipplers",
    "nked",
    "nos pondremos en contacto con usted",
    "npls",
    "nsfw images",
    "nude",
    "nudes",
    "nudity",
    "nuestro empleado le escribira en el chat",
    "nympho",
    "nymphomania",
    "octopussy",
    "omegle",
    "omorashi",
    "onlyf",
    "onlyfans",
    "onlyfanscom",
    "onlyfriendcom",
    "open legs",
    "open leg",
    "open show",
    "orgasm",
    "orgy",
    "our manager will contact",
    "paedophile",
    "paid for show",
    "pay for show",
    "paypal",
    "paypalcom",
    "paypalme",
    "pedophile",
    "pegging",
    "penis",
    "pensis",
    "phone sex",
    "piece of shit",
    "piss on me",
    "piss pig",
    "pissing",
    "pisspig",
    "play banana",
    "pleasure chest",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "poop chute",
    "poopchute",
    "porn",
    "porn video",
    "pornhub",
    "prince albert piercing",
    "pthc",
    "ptjb",
    "pubes",
    "puessy",
    "punany",
    "pussy",
    "pusy",
    "puzy",
    "pvt",
    "pytm",
    "quail",
    "queaf",
    "queef",
    "quim",
    "RAHOWA",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rectum",
    "redqueen115",
    "reverse cowgirl",
    "rimjob",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "RU18",
    "rusty trombone",
    "S2R",
    "Stormfront",
    "Sturmabteilung",
    "sm",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sex",
    "sexo",
    "sexy show",
    "sexy wife",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shitblimp",
    "show ass",
    "show milk",
    "show oss",
    "shrimping",
    "sikis",
    "skeet",
    "skillcashlive",
    "slanteye",
    "slap that",
    "slut",
    "smurf muffin",
    "snackvideocom",
    "snapchat",
    "snapchatcom",
    "snapfuck",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "spit on me",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "sprlvlink",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "strip",
    "strip4me",
    "style doggy",
    "su cuenta necesita confirmacion",
    "suck",
    "suicide girls",
    "suka",
    "sultry women",
    "superchatlive",
    "superlive",
    "suqrit",
    "swastika",
    "TLigram id",
    "ThickAzz",
    "Totenkopf",
    "take off",
    "tancredo",
    "tango mafia",
    "tango mafiya",
    "tango mafya",
    "taste my",
    "tea bagging",
    "telegram",
    "threesome",
    "throating",
    "throbbing",
    "ti contattera in chat",
    "tied up",
    "tight white",
    "tities",
    "titiez",
    "tits",
    "tongue in a",
    "toples",
    "topless",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tub girl",
    "tubgirl",
    "tushy",
    "twark",
    "twat",
    "twitchtv",
    "twink",
    "twinkie",
    "undies",
    "undressing",
    "upskirt",
    "urethra play",
    "urophilia",
    "vagina",
    "vaginaa",
    "vajina",
    "vdo",
    "vdos",
    "venmo",
    "venus mound",
    "vibrator",
    "violet wand",
    "viptango22",
    "virgin",
    "vorarephilia",
    "voyeur",
    "vulva",
    "wame",
    "wank",
    "wet dream",
    "wetback",
    "whatsapp",
    "white goo",
    "white power",
    "white pride",
    "whore",
    "wolfsangel",
    "with kid",
    "wrinkled starfish",
    "xhamster13desi",
    "xnx",
    "xvideos",
    "xx",
    "xxx",
    "yaoi",
    "yeah baby",
    "yeah girl",
    "yellow showers",
    "yiffy",
    "your banana",
    "your goo",
    "your videos",
    "yrs grl",
    "zoophilia"
]

export const chatOnlyBlacklistEs = [
    "Chulada",
    "Verga",
    "mojar",
    "bubis",
    "dar duro",
    "tener duro",
    "bragas",
    "lindas bubis",
    "lindas bbs",
    "virgen",
    "papalla",
    "tanga",
    "nalgona",
    "cacha",
    "cachos",
    "meu pau",
    "pararse",
    "pechos",
    "qlo",
    "desnudita",
    "sacar el culo",
    "nalgas infladas",
    "chupar",
    "perra",
    "nepe",
    "Pinche feo",
    "hija de puta de tu madre",
    "marica",
    "tomar leche",
    "joda",
    "joder",
    "Asesinato",
    "asno",
    "Bastardo",
    "Bragas",
    "Bollera",
    "Boludo",
    "Cabron",
    "Cabrón",
    "Caca",
    "Cagar",
    "Carajo",
    "Careverga",
    "Chingar",
    "Chocha",
    "Chucha",
    "Chupa",
    "Chupar",
    "Chupate",
    "Chupada",
    "Chupavergas",
    "Chupapollas",
    "Chupeton",
    "Chupo",
    "Colita",
    "Coger",
    "Cogerte",
    "Cojer",
    "Cojerte",
    "concha",
    "Concha de tu madre",
    "Conio",
    "Consolador",
    "Coño",
    "Coprofagía",
    "Cuca",
    "Cuerpo",
    "Culiao",
    "Culito",
    "Culo",
    "Cuerpazo",
    "Desnudar",
    "Desnudate",
    "Desnudo",
    "Desnuda",
    "Desnudita",
    "Drogas",
    "Esperma",
    "Estúpido",
    "Follador",
    "Follar",
    "Follarte",
    "Gilipichis",
    "Gilipollas",
    "Gueva",
    "Hacer una paja",
    "Haciendo el amor",
    "Heroína",
    "Huevo",
    "Huevón",
    "Hija de puta",
    "Hijaputa",
    "Hijo de puta",
    "Hijoputa",
    "hojueputica",
    "Joder",
    "Jodas",
    "Joto",
    "Jueputa",
    "Idiota",
    "Imbécil",
    "Jilipollas",
    "Kapullo",
    "Lameculos",
    "Lamer",
    "Leche",
    "Lencería ",
    "Lechito",
    "Lesbiana",
    "Maciza",
    "Macizorra",
    "mamada",
    "mamadita",
    "Mamahuevo",
    "Masturbar ",
    "Masturbarse",
    "Mastrubando",
    "Marica",
    "Maricon",
    "Mariconazo",
    "Mear",
    "Mierda",
    "Mojado",
    "Mojada",
    "Nalgazo",
    "Nalgas",
    "Nazi",
    "Ombligo",
    "Orina",
    "Paja",
    "Pajar",
    "Pajear",
    "Pajearme",
    "Perra",
    "Panocha",
    "Pendejo",
    "Pene",
    "Pezón",
    "Pecho",
    "Pechitos",
    "Petero",
    "Pelotudo",
    "Pierna",
    "Piernas",
    "Pinche",
    "Pis",
    "Privado video",
    "Prostituta",
    "Puta madre",
    "Quitate",
    "Racista",
    "Ramera",
    "Ropa interior",
    "Sádico",
    "Semen",
    "Sexo",
    "Sexo oral",
    "Soplagaitas",
    "Soplapollas",
    "tetas",
    "tetas grandes",
    "tia buena",
    "tragaleche",
    "travesti",
    "vagina",
    "violar",
    "verga",
    "vete a la mierda",
    "vulva",
    "zorra",
    "mi pene",
    "ese culo",
    "tener sexo",
    "muy caliente",
    "muy rico",
    "el sexo",
    "mi polla",
    "estoy masturbando",
    "hacer el amor",
    "tener sexo contigo",
    "un pene",
    "mi verga",
    "ver el coño",
    "colita",
    "sexis",
    "Mames",
    "follando",
    "fikiĝi",
    "fikiĝu",
    "fikilo",
    "fikklauno",
    "puta idea",
    "putadea",
    "bragas de abuela",
    "cuca",
    "Bubis",
    "Des nudate",
    "desnudate",
    "Mala leche",
    "Por jod@",
    "cuerpazo",
    "puta",
    "Mejor quítate eso"
]

export const chatOnlyBlacklistRu = [
    "bychara",
    "byk",
    "chernozhopyi",
    "dolboyeb",
    "ebalnik",
    "ebalo",
    "ebalom schelkat",
    "mudack",
    "opizdenet",
    "ostoeblo",
    "ostokhuitelno",
    "otebis",
    "otmudohat",
    "otpizdit",
    "otsosi",
    "padlo",
    "pedik",
    "perdet",
    "petuh",
    "pidar gnoinyj",
    "pizdyulina",
    "pizduk",
    "pizda",
    "pizdoi nakrytsja",
    "po khuy",
    "poimat na konchik",
    "poiti posrat",
    "podi kuevo",
    "poeben",
    "poluchit pizdy",
    "pokaju siski",
    "pokaji soski",
    "pososi moyu konfetku",
    "prissat",
    "proebat",
    "promudobladsksya pizdoproebina",
    "propezdoloch",
    "prosrat",
    "raspeezdeyi",
    "raspizdatyi",
    "razyebuy",
    "razyoba",
    "sebatsya",
    "shalava",
    "styervo",
    "siski",
    "sukin syn",
    "svodit posrat",
    "svoloch",
    "trakhatsya",
    "trimandoblydskiy pizdoproyob",
    "uebitsche",
    "ublyudok",
    "uboy",
    "v pizdu",
    "vafla",
    "vafli lovit",
    "vibrador",
    "vyperdysh",
    "vzdrochennyi",
    "yeb vas",
    "zaebat",
    "zaebis",
    "zalupa",
    "zalupat",
    "zasranetc",
    "zassat",
    "zloebuchy",
    "ахуенно",
    "ахуенна",
    "ахуенчик",
    "блядь",
    "ёб",
    "охуенна",
    "охуенно",
    "охуено",
    "охуена",
    "охуенчик",
    "пизды",
    "простітутка",
    "протітутка",
    "повія",
    "трахни",
    "трахну",
    "трахнути"
]

export const privateChatBlacklist = [
    "bigo",
    "bigolive",
    "superlive",
    "liveme",
    "tango",
    "639551402465",
    "639959173779",
    "Baby video",
    "boy vids",
    "boys under",
    "Buy bedios",
    "buy young",
    "childlove",
    "childlover",
    "D4UTH3R",
    "DAUGH",
    "daught3r",
    "daughter",
    "fuck my daughter",
    "Girl o1d",
    "girls under",
    "have daughter",
    "hot daughter",
    "hot son",
    "hot child",
    "he and me",
    "husband and wife",
    "I sell 🎥",
    "kiddie porn",
    "little girl please",
    "little show",
    "Me and her",
    "mega",
    "megalink",
    "Message me f u want buy",
    "Mom son",
    "play her",
    "play with young",
    "plyyng",
    "preteens",
    "Selling 🎥",
    "sex with little",
    "share sex",
    "show kid",
    "show her",
    "she anf megalink",
    "suck a baby",
    "Teen",
    "trading videos",
    "triple x",
    "two girls little",
    "U want buy",
    "underage",
    "U buy",
    "vendo 🎥",
    "video of young",
    "video Yong",
    "Videos and megalinks",
    "videos for trading",
    "Want bedios",
    "want child",
    "want kids",
    "Y O U N G",
    "yangbedeo",
    "yang4fun",
    "Yangvids",
    "Yes she 5",
    "yng",
    "yngplay",
    "yngvids",
    "You buy",
    "young video",
    "young videos",
    "youngen"
]

export const nameAndStatusBlacklist = [
    "🌭",
    "🌶",
    "🌽",
    "🍆",
    "🍌",
    "🍑",
    "🍼",
    "🪛",
    "👃",
    "👖👖",
    "👙",
    "👯",
    "💦",
    "📱",
    "📲",
    "📲📲",
    "📳",
    "📳📳",
    "📳📳📳",
    "🔞",
    "🖕",
    "😈zisters😋small",
    "🥒",
    "🥭🥭",
    "🦵",
    "🩱",
    "🩲🩲",
    "🍩",
    "⭕❌",
    "࿕",
    "ᑕᕼᑌT",
    "ᛋᛋ",
    "⚠",
    "✙",
    "❌❌❌",
    "卐",
    "ꑭ",
    "ꖦ",
    "0NLYF4NZ",
    "one1",
    "one guy one jar",
    "one cup two girls",
    "2 girls 1 cup",
    "2SiS",
    "2g1c",
    "2girls",
    "4YEO",
    "53X",
    "7yEar",
    "цп",
    "3arabporncom",
    "acrotomophilia",
    "admin",
    "administration",
    "administration tango",
    "adult private videos",
    "adult video",
    "adult videos",
    "adults inside",
    "advanced white society",
    "active",
    "aishole",
    "alabama hot pocket",
    "alaskan pipeline",
    "alohatubearabcom",
    "angel legs",
    "anilingus",
    "apeshit",
    "araborgasmcom",
    "arabsex1",
    "arabuncoveredcom",
    "arsehole",
    "aryan brotherhood",
    "atomwaffen",
    "atomwaffen division",
    "atrevidos",
    "auto erotic",
    "autoerotic",
    "awesome threesome",
    "azgin",
    "b00ty",
    "babeland",
    "babies",
    "baby",
    "baby batter",
    "baby juice",
    "babygirl show",
    "badly all night",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballz deep",
    "bangbros",
    "bareback",
    "barely legal",
    "barenaked",
    "bastard",
    "bastardo",
    "bastinado",
    "bathroom show",
    "baybis",
    "bb",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "beby",
    "bedios",
    "behanchod",
    "bensenlecom",
    "bestiality",
    "bg dck",
    "bhabhi",
    "bideo",
    "bideos",
    "bidio",
    "bidios",
    "big black",
    "big botty",
    "big boy",
    "big breasts",
    "big cook",
    "big daddy",
    "big dick",
    "big dk",
    "big guy",
    "big natural",
    "bigboobs",
    "biggy",
    "bigo",
    "bigovideotv",
    "bigsdig",
    "bigtitty",
    "big🍑",
    "bimbos",
    "birdlock",
    "birebir",
    "bitch",
    "bitsy",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blow job",
    "blow me",
    "blow your load",
    "blowjob",
    "blue waffle",
    "blumpkin",
    "blut und ehre",
    "blyat",
    "bollocks",
    "bondage",
    "boner",
    "bongacamscom",
    "boobie trap",
    "boobies",
    "boobs",
    "bood job",
    "boooobs",
    "boostyto",
    "booty",
    "booty call",
    "bootylover",
    "botty",
    "boytoy",
    "bqby",
    "brazzers",
    "breast",
    "breast friends",
    "brown showers",
    "brunette action",
    "bubble butt",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "buttcheeks",
    "butter age",
    "butter butt",
    "butter cup",
    "butthole",
    "buzzcastinfo",
    "call boy",
    "call girl",
    "cam4com",
    "camel toe",
    "camgirl",
    "camm bebe",
    "camscom",
    "camslut",
    "camsodacom",
    "camwhore",
    "candy crush",
    "cannabis",
    "capal sohw",
    "carpet muncher",
    "carpetmuncher",
    "cashapp",
    "cashme",
    "caution hot to handle",
    "ceepee",
    "censored",
    "chad",
    "chats meow",
    "chaturbatecom",
    "cheeky",
    "chicks with kinks",
    "child",
    "children",
    "chink",
    "chlen",
    "chocolate rosebuds",
    "chodai",
    "chudai",
    "cift",
    "cift sow",
    "ciipee",
    "circlejerk",
    "cleveland steamer",
    "CLIPS",
    "clit",
    "clitoris",
    "clover clamps",
    "clusterfuck",
    "Cocaine",
    "cock",
    "cocksucker",
    "coin",
    "coins",
    "connected",
    "control me",
    "coon",
    "coons",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coupl show",
    "couple",
    "couple show",
    "comtrollush",
    "cp",
    "cpl",
    "cplshow",
    "cracker",
    "creampie",
    "cshapp",
    "cucking",
    "cucumber",
    "cum",
    "сuminside",
    "cumming",
    "cunnilingus",
    "cunning stunts",
    "cunt",
    "cupel show",
    "cupple show",
    "cuttly",
    "daddy natives",
    "darkie",
    "das reich",
    "date rape",
    "daterape",
    "dau g her",
    "daught3r",
    "daughter",
    "daugt",
    "daugther",
    "deep throat",
    "deepthroat",
    "demo free",
    "dendrophilia",
    "detskoe",
    "dick",
    "dik",
    "dilda",
    "dildo",
    "dingleberries",
    "dingleberry",
    "dirty boys",
    "dirty girls",
    "dirty pillows",
    "dirty sanchez",
    "dirty secrets",
    "dogie style",
    "doing show",
    "dolcett",
    "doll baby",
    "domination",
    "dominatrix",
    "dommes",
    "donkey punch",
    "dope",
    "double dong",
    "double penetration",
    "dougthr",
    "dp action",
    "dpo4ep",
    "dpochep",
    "dripping",
    "dro4er",
    "drocher",
    "dry hump",
    "dught3r",
    "dugther",
    "dvda",
    "dyke",
    "ecchi",
    "ejaculation",
    "ELI5",
    "employee",
    "employее",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "evermorclub",
    "Fac you",
    "facecastlive",
    "fanstoriescom",
    "fack",
    "faggot",
    "family ties",
    "fancentrocom",
    "fanslycom",
    "fastest finger",
    "fastest finger first",
    "fath3r",
    "father",
    "fap",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "FGRN",
    "fidyo",
    "figging",
    "filthy boy",
    "filthy chicks",
    "fingerbang",
    "fingering",
    "fingers in mouth",
    "fisting",
    "fiuck",
    "flamneekcom",
    "flirt4freecom",
    "florian Geyer",
    "foot fetish",
    "footjob",
    "for call",
    "for go to",
    "for more",
    "for underwear",
    "four play",
    "foxy mister",
    "free show",
    "freess",
    "fresh teen",
    "frotting",
    "fsvegbuzzcastinfo",
    "fth3r",
    "fu ck you",
    "fucikig",
    "fuck",
    "fucked",
    "fuckmypakistanigfcom",
    "fucktards",
    "fudge packer",
    "fudgepacker",
    "fugpuggler",
    "fuick",
    "fuk",
    "fukko",
    "fukme",
    "full",
    "full enjoy",
    "full opan",
    "full sho",
    "full show",
    "futanari",
    "FYEO",
    "gang bang",
    "gasti",
    "gaughter",
    "gay",
    "gay sex",
    "genitals",
    "ghasti",
    "giant cock",
    "gift for vibrate",
    "girl for sale",
    "girls gone wild",
    "gmail",
    "GNRN",
    "go fuck",
    "go pri",
    "goatcx",
    "goatse",
    "god damn",
    "gokkun",
    "golden shower",
    "goo girl",
    "goodpoop",
    "google meet",
    "Google pay",
    "goregasm",
    "Gossip girls",
    "goyim",
    "gr0p",
    "gr0up",
    "great balls of fire",
    "grl",
    "grop",
    "grope",
    "group",
    "group sex",
    "group show",
    "grouplink",
    "grp",
    "grp show",
    "gruop",
    "grup",
    "GTKRWN",
    "gup links",
    "gurup",
    "haji",
    "hand job",
    "handjob",
    "hard core",
    "hardcore",
    "he and me",
    "heil hitler",
    "hentai",
    "heroin",
    "hillbilly",
    "hips",
    "homoerotic",
    "honey roast chat",
    "honeybuns",
    "honeyButter",
    "honkey",
    "hooker",
    "horney",
    "horny",
    "horny roast chat",
    "horst wessel",
    "hot",
    "hot butt",
    "hot carl",
    "hot chick",
    "hot couple",
    "hot lips",
    "hot mama",
    "hot stuff",
    "hotcom12",
    "hotmartcom",
    "hotshot",
    "hotshow",
    "hottiee",
    "hotties little",
    "how to kill",
    "how to murder",
    "htp",
    "httq",
    "huge fat",
    "human Targets",
    "humping",
    "hunt for Hot",
    "i pay for",
    "idv",
    "imlivecom",
    "imoim",
    "inbox msg",
    "incest",
    "inches",
    "interactive game connected",
    "interactive toy",
    "intercourse",
    "isis",
    "italian stallion",
    "IWSN",
    "jack off",
    "jail bait",
    "jailbait",
    "jazcash",
    "jbv",
    "jelly donut",
    "jellybae",
    "jellybean",
    "jellyboo",
    "jerk off",
    "jew",
    "jews",
    "jigaboo",
    "jiggaboo",
    "jigger",
    "jiggerboo",
    "jizz",
    "joicom",
    "joint",
    "jrup lnk",
    "juggs",
    "justforfanscom",
    "kama sutra followers",
    "ketamine",
    "kids next door",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "kitty",
    "kkoarzdvws",
    "knobbing",
    "koficom",
    "kofilinkcom",
    "KPC",
    "l3sbico",
    "ladies with hole",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "lesb",
    "lesbian",
    "lesbis",
    "lesby",
    "letsgo11",
    "lez show",
    "lezb",
    "lezbn",
    "lezshow",
    "likeevideo",
    "lilhole",
    "link",
    "links",
    "linktr",
    "linktree",
    "litle15year",
    "little gurl",
    "little Mama",
    "little show",
    "little sis",
    "livejasmincom",
    "lolita",
    "love without boundaries",
    "lovemaking",
    "lovense",
    "lover boy",
    "loverboy",
    "lovey Butt",
    "loyalfanscom",
    "lrig elttiL",
    "lsb",
    "lsd",
    "luscious",
    "lush",
    "lush connected",
    "lusty",
    "lеsblаnSisters",
    "m0m",
    "maderation",
    "make it vibrate",
    "make me come",
    "male squirting",
    "mama",
    "mamgirl",
    "mamy",
    "manager tango",
    "marijuana",
    "masti",
    "mastrub",
    "masturabtion",
    "masturb",
    "masturbastou",
    "masturbate",
    "masturbation",
    "masturbtion",
    "masty",
    "me and you",
    "megacpcp",
    "meine ehre heisst treue",
    "melons",
    "menage a trois",
    "mescaline",
    "message me",
    "methamphetamine",
    "midnight moans",
    "milf",
    "milfhunters",
    "milk and cookies",
    "milkyyzz",
    "missionary position",
    "mmsmall",
    "moderation",
    "modern family",
    "mom",
    "mom and",
    "mom show",
    "mommy",
    "momy",
    "monkey butt",
    "morning glory",
    "mother",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "mssg",
    "muff diver",
    "muffdiving",
    "mum sun",
    "mummy",
    "muslim",
    "my little sister",
    "my number",
    "my pnis",
    "my sister H0T",
    "mydirtyhobbycom",
    "myfreecamscom",
    "mzsg",
    "mყ ɯԋαƚʂαρρ ɳυɱⴆҽɾ",
    "m🥵msmall",
    "N0UDES",
    "naeb",
    "nahui",
    "nambla",
    "nasty videos",
    "naughtiness",
    "naughty Lodge",
    "nawashi",
    "nend sudes",
    "neonazi",
    "NFOC",
    "nifoc",
    "nig nog",
    "nigga",
    "nigger",
    "nimphomania",
    "nipal",
    "niple",
    "niples",
    "niplez",
    "nkd",
    "nmbr",
    "nsfw images",
    "nude",
    "nudity",
    "num nums",
    "nympho",
    "nymphomania",
    "o to o sh",
    "octopussy",
    "odd duck",
    "ofans",
    "ofanz",
    "official tango",
    "officialtango",
    "oidiv",
    "omeglecom",
    "omorashi",
    "only fans",
    "only fanz",
    "onlyf",
    "onlyfan",
    "onlyfans",
    "onlyfanscom",
    "onlyfanz",
    "onlyfriendclub",
    "onlysfans",
    "open",
    "open legs",
    "opnd",
    "oral",
    "orgasm",
    "orgy",
    "ozel",
    "ozeldeyim",
    "pa pal",
    "paedophile",
    "paidshow",
    "palooka",
    "papal",
    "papito",
    "parinka00",
    "parivte",
    "patreon",
    "payment",
    "paypal",
    "paypalcom",
    "paypalme",
    "paytm",
    "peanut butter",
    "pedobear",
    "pedophile",
    "pegging",
    "penis",
    "perversa",
    "pezda",
    "phone sex",
    "pickle pie",
    "pidar",
    "pidarass",
    "piece of shit",
    "piss pig",
    "pissing",
    "pisspig",
    "pizda",
    "play banana",
    "play my popka",
    "playboy",
    "pleasure chest",
    "plyyng",
    "polak",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "poop chute",
    "poopchute",
    "porn",
    "porn video",
    "pornhub",
    "porno",
    "pornography",
    "potty mouths",
    "pretty little liars",
    "price",
    "prince albert piercing",
    "priya ji",
    "pthc",
    "ptjb",
    "pubes",
    "puccy",
    "puisi",
    "punany",
    "pusi",
    "pusstight",
    "pussy",
    "pussycat",
    "pusulaagencycom",
    "pusy",
    "puucy",
    "puzy",
    "quail",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "raging boner",
    "rahowa",
    "raping",
    "rapist",
    "rectum",
    "redneck",
    "retard",
    "reverse cowgirl",
    "rimjob",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rusty trombone",
    "S2R",
    "s3x",
    "s3xx",
    "sadism",
    "salvia",
    "santorum",
    "saptacha",
    "sassy lass",
    "saxy",
    "saxy saxy",
    "scat",
    "schlong",
    "scissoring",
    "secretvidz",
    "seks",
    "seksi",
    "sekz",
    "sell video",
    "selling vid",
    "semen",
    "sex",
    "sex dealer",
    "sex demon",
    "sex enchantress",
    "sex warlock",
    "sex witch",
    "sex zombie",
    "sexiness",
    "sexo",
    "sexsi",
    "sexual healing",
    "sexy",
    "sexy beast",
    "sexy lady",
    "sexy legs",
    "sexy mama",
    "sexy mister",
    "sexy pie",
    "sexy stallion",
    "sexy thang",
    "sexy thing",
    "sexy tickles",
    "sexy twoshoes",
    "sh0wpossi",
    "shaved",
    "shaved beaver",
    "shaved kitty",
    "shaved pussy",
    "she and me",
    "shemale",
    "shibari",
    "shitblimp",
    "shitty",
    "sho wԋαƚʂAρρ",
    "shota",
    "show ass",
    "shower show",
    "shrimping",
    "shved",
    "shyt",
    "shоwеr party",
    "sh😻ved ki😻ty",
    "sikis",
    "Siski",
    "sister brother",
    "sisters",
    "sisters small",
    "skeet",
    "skillcashlive",
    "skype show",
    "slanteye",
    "slut",
    "sm",
    "small",
    "small sisters",
    "smallanddaught3r",
    "smallbuddyfun",
    "smll and daught3r",
    "smurf muffin",
    "snackvideocom",
    "snapchatcom",
    "snapfuck6shycom",
    "snp cht",
    "snatch",
    "snowballing",
    "so hot",
    "sodomize",
    "sodomy",
    "soobquotescom",
    "sow",
    "soydur skype show",
    "soydur4com",
    "soydurme",
    "special content",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "sprlvlink",
    "spunk",
    "squirt",
    "squit",
    "stoner",
    "stormfront",
    "strangers with candy",
    "strap on",
    "strapon",
    "strappado",
    "strip",
    "strip club",
    "stripchatcom",
    "striptiz",
    "sturmabteilung",
    "style doggy",
    "suck",
    "sugar and boo",
    "sugar lips",
    "suicide girls",
    "sultry women",
    "superchatlive",
    "swallow",
    "swastika",
    "sweet cheeks",
    "sweet kitten",
    "sweet lover",
    "sweet pea",
    "sweetie pie",
    "sweetiekins",
    "swinger",
    "sxy",
    "sаху",
    "s🥚s",
    "tainted love",
    "take off",
    "tancredo",
    "tanger",
    "tango",
    "tango admin",
    "tango auction",
    "tango discounts",
    "tango events",
    "tango gifts",
    "tango guardian",
    "tango mafia",
    "tango manager",
    "tango moderator",
    "tango official",
    "tango offiicial",
    "tango operator",
    "tango Store",
    "tango support",
    "tangoadm",
    "tangofuc",
    "tangoo bideos",
    "tangoofficial",
    "tangorefill",
    "tangorefillcom",
    "taste my",
    "tea bagging",
    "tea beggars",
    "teacup",
    "teen",
    "teen video",
    "tektek",
    "telegram",
    "the finger pullers",
    "the naughty zoo",
    "the sister wives",
    "thickalicious",
    "thickAzz",
    "threesome",
    "throating",
    "tibble nits",
    "tied up",
    "tight white",
    "tities",
    "titiez",
    "tits",
    "titty",
    "titz",
    "tlgm",
    "tlgram",
    "tligram",
    "tligram id",
    "tligrm",
    "tongue in a",
    "topless",
    "tosser",
    "totenkopf",
    "towelhead",
    "toy connected",
    "toy on",
    "toyplay",
    "tranny",
    "tribadism",
    "tubgirl",
    "tushy",
    "twat",
    "twerk",
    "twitchtv",
    "two Fingers",
    "two girls little",
    "two girls one cup",
    "twommsmall14year",
    "u and me",
    "uncovered power",
    "undressing",
    "unlockdcom",
    "unsatisfied Geeks",
    "upskirt",
    "urethra play",
    "urophilia",
    "ussy",
    "vagina",
    "vaginaa",
    "vajina",
    "vatsap",
    "venmo",
    "venus mound",
    "vi2240",
    "vibrate",
    "Vibrations",
    "vibrator",
    "victory in da feet",
    "vid3",
    "vide",
    "video call",
    "video sell",
    "videotango",
    "vidyo",
    "vidyoo",
    "violet wand",
    "virgin",
    "VİDYO",
    "vorarephilia",
    "voucher",
    "voyeur",
    "vudeo",
    "vulva",
    "vıdo",
    "wahtaspp",
    "wame",
    "wank",
    "wapp",
    "wapvideoscom",
    "watsabe",
    "watsap",
    "we share genes",
    "weed",
    "weekend lovers",
    "wet dream",
    "wetback",
    "wett",
    "whap",
    "whatcmefap",
    "whapa",
    "whapsap",
    "whatap",
    "whataspp",
    "whatcap",
    "whatp",
    "whats app",
    "whats no",
    "whatsap",
    "whatsapp",
    "whatsaup",
    "whatshop",
    "whatshop show",
    "whatshow",
    "whatsop",
    "whatsup",
    "whatzap",
    "whazzp",
    "whipcracker",
    "white power",
    "white pride",
    "whore",
    "whp",
    "whsp",
    "wht",
    "whtp",
    "whtpp",
    "whts",
    "whtsa",
    "whtsap",
    "whtshopp",
    "whtsp",
    "whtspp",
    "whtsuhp",
    "wh😎re",
    "wiggle nibble",
    "wolfsangel",
    "wookie",
    "wotsap",
    "wotsap nmbr",
    "wrapping men",
    "wrinkled starfish",
    "wsp",
    "wstp",
    "wtf",
    "wtp",
    "wtseip",
    "wtsep",
    "wtsp",
    "wttsp",
    "wtzp",
    "wwtp",
    "x3vd",
    "xcamscom",
    "xhamster13desi",
    "xshow",
    "xtra Hot",
    "y ng",
    "yang",
    "yangvids",
    "yaoi",
    "years",
    "yellow showers",
    "yiffy",
    "yng",
    "yng4U",
    "yngply",
    "you and me",
    "you and me alon",
    "you and me alone",
    "you and me lonely",
    "you finish",
    "you me",
    "zoophilia",
    "§ėxý Łóvëř",
    "Çift",
    "ÇİFT",
    "ÇİFT SİKİŞ",
    "çpĺ",
    "özel",
    "Özele",
    "ģŕòùp",
    "ƒυℓℓ σρєη şђow",
    "σηє 𝘁𝗼 σηє",
    "σρєη şђow",
    "Вооbs",
    "момму",
    "тits",
    "ابعت صورة",
    "ابعت فيديو",
    "ابغى اطفال",
    "ابغى طفل",
    "ابغى ولاد",
    "ابغى ولد",
    "ابي اطفال",
    "ابي اولاد",
    "ابي طفل",
    "ابي ولد",
    "ارسل صورة",
    "اريد طفل",
    "اريد ولد",
    "اشتري",
    "الجروب",
    "الخاص",
    "القروب",
    "النيك",
    "انا وانت لوحدنا",
    "اندريج",
    "بخ",
    "برايفت",
    "برايفيت",
    "بزب كبير",
    "بنات صغار",
    "بنات صغيرة",
    "بنت صغيرة",
    "بنت مزة",
    "بنت مولعة",
    "بنت نار",
    "بنتان صغيرتان",
    "بيع",
    "تريد تشتري",
    "جروب",
    "خاص",
    "دون السن",
    "راسلني اذا بدك تشتري",
    "راسلني اذا تريد تشتري",
    "رقم الجوال",
    "رقمي",
    "رقمي الخاص",
    "روابط فيديو",
    "سترينغ",
    "سكس مع صغار",
    "سوتيان",
    "شراء اطفال",
    "شراء بنات",
    "شراء بنت",
    "شراء صغار",
    "شراء فتيات",
    "صدر",
    "صغار",
    "طرش صورة",
    "طفلة",
    "طفلة مزة",
    "طفلة مولعة",
    "طفلة نار",
    "طفلتان",
    "عرض استحمام",
    "عرض خاص",
    "عندي بنات",
    "عندي بنت",
    "عندي فتات",
    "عندي ولد",
    "فتات صغيرة",
    "فتاتان صغيرتان",
    "فرجي الطفل",
    "فرجي الولد",
    "فرجيها",
    "فيديو",
    "فيديو اطفال",
    "فيديو بنات",
    "فيديو روابط",
    "فيديو صغار",
    "فيديو فلد",
    "فيديو ولاد",
    "فيديو ولد",
    "قروب",
    "كس",
    "لبرايفت",
    "لدي ولد",
    "لعب صغار",
    "لعب مع صغار",
    "للخااص",
    "للخاص",
    "لواحدك",
    "مراهق",
    "مراهقة",
    "مقطع اطفال",
    "مقطع بنات",
    "مقطع صغار",
    "مقطع ولاد",
    "مقطع ولد",
    "مكالمه فيديو على الخاص",
    "ملابس داخلية",
    "هو وانا",
    "هي وانا",
    "واحد لواحد",
    "وحدك",
    "وري الطفل",
    "وري الولد",
    "وريها",
    "ولاد دون السن",
    "ولاد صغار",
    "ولد مولع",
    "ولد نار",
    "يوجد بنات",
    "يوجد بنت",
    "يوجد فتات",
    "يوجد ولد",
    "ইম",
    "ইমু",
    "ইমুতে",
    "ইমো",
    "ইমোতে",
    "কয়েন",
    "গুরুপ",
    "গোসল শো",
    "গ্রুপ সো কাপল",
    "টাকা",
    "টাকায়",
    "ফাকিং",
    "বিকাশ",
    "সেক্স",
    "হট কাপল শো",
    "হোয়াটসঅ্যাপ",
    "வாட்ஸ்அப்",
    "ꟼﾌՁ8Ʒ8ꟼ4ⳒƷ",
    "ꟼﾌՁზ3ზꟼ4ნᙣ"
]